services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    # Load ALL API keys and Config from your .env file
    env_file:
      - .env
